### ISSUE TITLE
Is there a plan to release the code?

### ISSUE THREAD

**Issue by thiswinex** [WenjiaWang0312/Zolly#2]
Your work is great and I can't wait to see the code! Do you still plan to release it?

**Comment by WenjiaWang0312** [comment]
Hi, I have been busy recent months. I plan to release the code right after the ICCV conference. Maybe 2 weeks later. Thanks~

**Comment by thiswinex** [comment]
> Hi, I have been busy recent months. I plan to release the code right after the ICCV conference. Maybe 2 weeks later. Thanks~

Hi, sorry to bother again in your busy schedule. Do you have a certain time to release the code recently?

**Comment by WenjiaWang0312** [comment]
> > Hi, I have been busy recent months. I plan to release the code right after the ICCV conference. Maybe 2 weeks later. Thanks~
> 
> Hi, sorry to bother again in your busy schedule. Do you have a certain time to release the code recently?

Sorry for the late release. I have rushed the basic framework and it can be trained. I shall train a new checkpoint recently.
