### ISSUE TITLE
Demo and pretrained checkpoint

### ISSUE THREAD

**Issue by CumaOzavci** [WenjiaWang0312/Zolly#3]
Are you planning to release demo script and pretrained checkpoint?

**Comment by WenjiaWang0312** [comment]
Hi, thanks for your interest. I will release it after the Chinese New Year.

**Comment by linjing7** [comment]
+1. Zolly is very interesting. Looking forward to your demo script.

**Comment by tszhang97** [comment]
Any update?

**Comment by nibox** [comment]
Hi, I would also be interested in trying out Zolly. Are there any updates?

**Comment by WenjiaWang0312** [comment]
Sorry for the delay! Please try it. I did not use detection so the demo could be bad on some images.
